toolbar1: undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
toolbar2: table | fullscreen | code
plugins:
  - table
  - fullscreen
  - link image
  - code
  - preview
  - charmap